- hosts: create_vm
  remote_user: root

  pre_tasks:
  - name: Include les variables de la VM
    include_vars:
      file: "/applis/ansible/ans-create-vm/host_vars/{{ inventory_hostname }}.yml"
  - name: Inclure les variables du projet
    include_vars:
      file: "/applis/ansible/ans-create-vm/project-vars/proxmox_vm.yml"
  - name: Sourcer le vault
    include_vars:
      file: "/applis/ansible/ans-create-vm/vault/{{ project_vault }}.yml"

  tasks:
  - name: Include les roles
    include_role:
      name: role-configure-repos-020
