---
- hosts: create_vm
  remote_user: root
  gather_facts: no

  pre_tasks:
  - name: Inclure les variables du projet
    include_vars:
      file: "/applis/ansible/ans-create-vm/project-vars/proxmox_vm.yml"
  - name: Inclure les variables d'IPA
    include_vars:
      file: "/applis/ansible/ans-create-vm/project-vars/ipa.yml"
  - name: Include les variables de la VM
    include_vars:
      file: "/applis/ansible/ans-create-vm/host_vars/{{ groups['create_vm'][0] }}.yml"
  - name: Sourcer le vault
    include_vars:
      file: "/applis/ansible/ans-create-vm/vault/{{ project_vault }}.yml"

  tasks:
  - name: Include les roles
    include_role:
      name: role-configure-ipa-client-000
      allow_duplicates: false
