---
- hosts: zabbix_agent
  remote_user: root

  pre_tasks:
  - name: Inclure les variables du projet
    include_vars:
      file: "/applis/ansible/ans-create-vm/project-vars/zabbix_client.yml"
  - name: Inclure les variables de la VM
    include_vars:
      file: "/applis/ansible/ans-create-vm/host_vars/{{ inventory_hostname }}.yml"
  - name: Sourcer le vault
    include_vars:
      file: "/applis/ansible/ans-create-vm/vault/{{ project_vault }}.yml"

  tasks:
  - name: Inclure les roles
    include_role:
      name: role-zabbix-agent-000
      allow_duplicates: false
